name: Deploy Docker image

on:
  push:
    tags:
      - "*"
  create:
    tags:
      - "*"
  workflow_dispatch:

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  REMOTE_ORG: LemmyNet
  REMOTE_REPO: lemmy
  REMOTE_BRANCH: main
  LOCAL_ORG: lemmynsfw
  LOCAL_REPO: lemmy
  LOCAL_BRANCH: main
  POSTFIX: lemmynsfw

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.owner }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.LOCAL_ORG }}/${{ env.LOCAL_REPO }}:${{ github.ref_name }}
          file: docker/Dockerfile
          build-args: |
            RUST_RELEASE_MODE=release
