name: Deploy Docker Image

on:
  push:
    tags:
      - "*"

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  REMOTE_ORG: LemmyNet
  REMOTE_REPO: lemmy
  REMOTE_BRANCH: main
  LOCAL_ORG: lemmynsfw
  LOCAL_REPO: lemmy
  LOCAL_BRANCH: main
  POSTFIX: lemmynsfw

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ LOCAL_ORG }}
          password: ${{ PERSONAL_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ LOCAL_ORG }}/${{ LOCAL_REPO }}:${{ github.ref }}
