name: Sync tags

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  REMOTE_ORG: LemmyNet
  REMOTE_REPO: lemmy
  REMOTE_BRANCH: main
  LOCAL_ORG: lemmynsfw
  LOCAL_REPO: lemmy
  LOCAL_BRANCH: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add upstream https://github.com/${{ env.REMOTE_ORG }}/${{ env.REMOTE_REPO }}.git
          git fetch --tags --prune --prune-tags upstream
          LAST_TAGS=$(git tag -l --sort=-committerdate | grep -v "lemmynsfw" | head -n 10)
          wget -O /tmp/diff.patch https://github.com/${REMOTE_ORG}/${REMOTE_REPO}/compare/${REMOTE_BRANCH}...${LOCAL_ORG}:${LOCAL_REPO}:${LOCAL_BRANCH}.patch
          for tag in $LAST_TAGS; do
            if [ $(git tag -l "$tag"-lemmynsfw) ]; then
              continue
            fi
            git checkout -b $tag $tag
            git apply --reverse /tmp/diff.patch
            git commit -m "Apply patch from ${REMOTE_ORG}/${REMOTE_REPO}#${tag}"
            git tag $tag-lemmynsfw
            git push origin tag $tag-lemmynsfw
            git checkout ${{ env.LOCAL_BRANCH }}
            git branch -D $tag
          done
