name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: lemmynsfw
          base: main
          head: main
      - name: Fetch all tags from upstream and prune
        run: |
          git remote add upstream https://github.com/LemmyNet/lemmy.git
          git fetch --tags --prune --prune-tags upstream
      - name: Push all tags to origin
        run: |
          git push origin --tags
