name: Sync tags

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  REMOTE_ORG: LemmyNet
  REMOTE_REPO: lemmy
  REMOTE_BRANCH: main
  LOCAL_ORG: lemmynsfw
  LOCAL_REPO: lemmy
  LOCAL_BRANCH: main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync tags
        uses: chachako/tags-sync@v1.0.1
        with:
          # github-token: ${{ env.PERSONAL_TOKEN }}
          base-repository: ${{ env.REMOTE_ORG }}/${{ env.REMOTE_REPO }}
          head-repository: ${{ env.LOCAL_ORG }}/${{ env.LOCAL_REPO }}
          # apply-patch: https://github.com/${{ env.REMOTE_ORG }}/${{ env.REMOTE_REPO }}/compare/${{ env.REMOTE_BRANCH }}...${{ env.LOCAL_ORG }}:${{ env.LOCAL_REPO }}:${{ env.LOCAL_BRANCH }}.patch
          # patch-message: Apply patch from ${apply-patch}
          # patch-author: ${{ github.actor }}
          # patch-author-email: github-actions[bot]@users.noreply.github.com
          # patch-committer: ${{ github.actor }}
          # patch-committer-email: github-actions[bot]@users.noreply.github.com
