name: Sync tags

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  REMOTE_ORG: LemmyNet
  REMOTE_REPO: lemmy
  REMOTE_BRANCH: main
  LOCAL_ORG: lemmynsfw
  LOCAL_REPO: lemmy
  LOCAL_BRANCH: main
  POSTFIX: lemmynsfw

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Sync tags
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/${{ env.REMOTE_ORG }}/${{ env.REMOTE_REPO }}.git
          git fetch --tags --prune --prune-tags upstream
          LAST_TAGS=$(git tag -l --sort=-committerdate | grep -v ${{ env.POSTFIX }} | head -n 10)
          git diff --cached --full-index upstream/${{ env.REMOTE_BRANCH }} > /tmp/diff.patch
          for tag in $LAST_TAGS; do
            if [ $(git tag -l "$tag"-${{ env.POSTFIX }}) ]; then
              continue
            fi
            git checkout -b $tag $tag
            git apply /tmp/diff.patch
            git add .
            git commit -m "Apply NSFW patch"
            git tag $tag-${{ env.POSTFIX }}
            git push origin tag $tag-${{ env.POSTFIX }}
            git checkout ${{ env.LOCAL_BRANCH }}
            git branch -D $tag
          done
