name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click

env:
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  REMOTE_ORG: LemmyNet
  REMOTE_REPO: lemmy

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fork main branch
        uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ env.PERSONAL_TOKEN }}
          owner: ${{github.repository_owner}}
          base: main
          head: main
          ignore_fail: true
      - name: Checkout new tags to branches
        id: checkout-tags
        uses: chachako/checkout-tags@v1
        with:
          base: ${{ env.REMOTE_ORG }}/${{ env.REMOTE_REPO }}
          overwrite: true
          # don't include alpha versions
          filter: ".*alpha.*"
          token: ${{ env.PERSONAL_TOKEN }}

      - name: Push all new branches
        run: |
          while read branch; do
            git push origin $branch
          done <<< "${{ steps.checkout-tags.outputs.branches }}"
